prometheus-operator:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.kube
    sidecar:
      dashboards:
        enabled: true

  nodeExporter:
    serviceMonitor:
      relabelings:
        - action: replace
          replacement: k3s-default
          sourceLabels:
            - __address__
          targetLabel: cluster
