apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./all.yaml

patchesStrategicMerge:
  - overlays/traefik-dashboard-service.yaml
  - overlays/traefik-dashboard-ingress.yaml

namespace: ingress