traefik:
  rbac:
    enabled: true
  metrics:
    prometheus:
      enabled: true
  kubernetes:
    ingressEndpoint:
      useDefaultPublishedService: true
  dashboard:
    enabled: true
    domain: traefik.kube
    statistics:
      recentErrors: 10
