apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: prometheus-operator-resources
    repoURL: https://github.com/frimik/tmtowtdi-deployments
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus-operator
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/validation
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
  syncPolicy:
    automated:
      selfHeal: true
      prune: false