apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-x", "-c"]
        args: ["helm repo add stable https://kubernetes-charts.storage.googleapis.com && helm dep build"]
      generate:
        command: ["/bin/sh", "-x", "-c"]
        args: ["helm template --release-name $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE . > all.yaml && kustomize edit set namespace $ARGOCD_APP_NAMESPACE && kustomize build"]
