apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/install.yaml
  - base/ingress.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

- path: overlays/production/argocd-application-controller-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-application-controller
    version: v1

namespace: argocd

#images:
#- name: argoproj/argocd
#  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
#  newTag: 1.6.0-1b0421c3
#- name: argoprojlabs/argocd-notifications
#  newName: docker.pkg.github.com/argoproj-labs/argocd-notifications/argocd-notifications
#  newTag: 0.7.0-a4b66bf8
