apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  source:
    path: traefik
    repoURL: https://github.com/frimik/tmtowtdi-deployments
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  project: default
  syncPolicy:
    automated: {}
  