apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dep build"]
      generate:
        command: [sh, -c]
        args: ["helm template . > all.yaml && kustomize build"]
