apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-collection
  namespace: argocd
spec:
  project: default
  source:
    path: prometheus-operator-collection
    repoURL: https://github.com/frimik/tmtowtdi-deployments
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-operator
  syncPolicy:
    automated:
      selfHeal: false
      prune: false