apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  source:
    path: traefik
    repoURL: https://github.com/frimik/tmtowtdi-deployments
    targetRevision: HEAD
  plugin:
    name: kustomized-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  project: default
  syncPolicy:
    automated:
      selfHeal: true
