resources:
  - argocd.yaml
  - traefik-ns.yaml
  - traefik.yaml
  - prometheus-operator-ns.yaml
  - prometheus-operator-collection.yaml
  - kubeview-ns.yaml
  - kubeview.yaml
  - podinfo-ns.yaml
  - podinfo.yaml
  - argocd-notifications-ns.yaml
  - argocd-notifications.yaml